### ISSUE TITLE
pom dependency problem for org.aksw + gerbil.nif.transfer

### ISSUE THREAD

**Issue by eeelnico** [quhfus/DoSeR#5]
when building with maven, there is an error:
Message:
[ERROR] Failed to execute goal on project doser-gerbilrest:
Could not resolve dependencies for project doser.sub:doser-gerbilrest:war:0.6:
Could not find artifact org.aksw:gerbil.nif.transfer:jar:0.0.1 in spotlight-releases-repository (https://github.com/dbpedia-spotlight/maven-repo/raw/master/releases)

/doser-gerbilrest/pom.xml
the following dependency cannot be resolved:
        <dependency>
            <groupId>org.aksw</groupId>
            <artifactId>gerbil.nif.transfer</artifactId>
            <version>0.0.1</version>
        </dependency>

**Comment by quhfus** [comment]
Fixed!

Thank you for the report
